services:
  database:
    container_name: mega-sena-data-api-postgres
    image: 'postgres:16'
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data:z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
    name: "mega-sena-data-api-database"
