CREATE TABLE IF NOT EXISTS mega_sena_records (
                                   id SERIAL NOT NULL,
                                   created_at TIMESTAMP DEFAULT current_timestamp,
                                   updated_at TIMESTAMP DEFAULT current_timestamp,
                                   concurso INTEGER,
                                   data_do_sorteio DATE,
                                   bola1 INTEGER,
                                   bola2 INTEGER,
                                   bola3 INTEGER,
                                   bola4 INTEGER,
                                   bola5 INTEGER,
                                   bola6 INTEGER,
                                   ganhadores_6_acertos INTEGER,
                                   cidade_UF VARCHAR,
                                   rateio_6_acertos VARCHAR,
                                   ganhadores_5_acertos INTEGER,
                                   rateio_5_acertos VARCHAR,
                                   ganhadores_4_acertos INTEGER,
                                   rateio_4_acertos VARCHAR,
                                   acumulado_6_acertos VARCHAR,
                                   arrecadacao_total VARCHAR,
                                   estimativa_premio VARCHAR,
                                   acumulado_sorteio_especial_mega_da_virada VARCHAR,
                                   observacao VARCHAR,
                                   PRIMARY KEY (id)
);
